# Generated by Django 6.1.1 on 2026-09-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='test',
        ),
    ]
