# Generated by Django 6.1.1 on 2026-09-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_entry_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table=None,
        ),
    ]
